version: '3.8'

services:
  mt5:
    build:
      context: backend/mt5
      dockerfile: Dockerfile
    container_name: mt5
    volumes:
      - ./config:/config
    environment:
      - DISPLAY=:0
      - WINEARCH=win64
      - WINEPREFIX=/config/.wine
      - CUSTOM_USER=admin
      - PASSWORD=password
    ports:
      - "3000:3000"  # VNC web interface
      - "5001:5001"  # API port
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge
